name: ci

on:
  push

jobs:
  set-environment:
    uses: ./.github/workflows/part.yml
  get-environment:
    runs-on: ubuntu-latest
    needs: set-environment
    steps:
      - name: Get env
        run: |
          echo TEST_ENV=$TEST_ENV
